# Generated by Django 3.2.19 on 2023-06-22 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0002_event_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('concert', 'Concert'), ('theater', 'Theater'), ('formation', 'Formation')], default='theater', max_length=20),
        ),
    ]
