# Generated by Django 3.2.19 on 2023-06-25 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0005_coupon_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='title',
            field=models.CharField(default='abonnement-client', max_length=100),
        ),
    ]
